version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - backend

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: menudb
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "3306:3306"
    networks:
      - backend

networks:
  backend: